insert into authors (name, description) values ('Willi Murricanes', 'Fruits dipped in rich chocolate, perfect for desserts.');
insert into authors (name, description) values ('Brod Tuson', 'Supportive pillow that provides comfort while traveling.');
insert into authors (name, description) values ('Rosaline Milthorpe', 'Wireless microphone for singing and performances.');
insert into authors (name, description) values ('Sibelle Jaycox', 'Crunchy granola with toasted coconut flakes, perfect for breakfast or snacks.');
insert into authors (name, description) values ('Lynn Wathey', 'Healthy energy bites made with oats and natural sweeteners.');
insert into authors (name, description) values ('Lenard Rillatt', 'Convenient belt with pockets for easy access to tools while gardening.');
insert into authors (name, description) values ('Alyson Giroldo', 'Portable folding camping chair with cup holder.');
insert into authors (name, description) values ('Humphrey McComb', 'Complete set for mixing cocktails at home.');
insert into authors (name, description) values ('Raffaello Jovis', 'Multi-angle stand for easy viewing of devices.');
insert into authors (name, description) values ('Niko Ivens', 'Reusable microfiber cloths for environmentally friendly cleaning.');
insert into authors (name, description) values ('Jacky Fried', 'Stylish wall art to enhance home decor.');
insert into authors (name, description) values ('Ignaz Grassett', 'Refreshing dressing made with avocado and lime, perfect for salads.');
insert into authors (name, description) values ('Gratiana Christofle', 'Sweet and gooey cinnamon rolls, ready to bake.');
insert into authors (name, description) values ('Lena Kiossel', 'Healthy, crunchy kale chips, a nutritious snack.');
insert into authors (name, description) values ('Dominica Fendlen', 'Crunchy granola with toasted coconut flakes, perfect for breakfast or snacks.');
insert into authors (name, description) values ('Darsey Arnowitz', 'Classic ranch dressing for salads and dipping.');
insert into authors (name, description) values ('Cassie Ronan', 'Rich and flavorful tomato sauce for pasta or pizza.');
insert into authors (name, description) values ('Lizbeth Shore', 'Roasted Brussels sprouts drizzled with balsamic glaze.');
insert into authors (name, description) values ('Doralynne Copnall', 'Fresh baby spinach leaves, great for salads and smoothies.');
insert into authors (name, description) values ('Charlton Kippins', 'Monitor and interact with your pet remotely with this camera.');
insert into authors (name, description) values ('Trix Ahearne', 'Passive noise reduction headphones for focus.');
insert into authors (name, description) values ('Jacki Spencelayh', 'Rich and smooth cold brew coffee concentrate, just add water or milk.');
insert into authors (name, description) values ('Rosemonde Vaszoly', 'Frozen mango chunks for smoothies or snacking.');
insert into authors (name, description) values ('Elwyn Flowith', 'Comfortable and adjustable harness for dogs.');
insert into authors (name, description) values ('Zia Earngy', 'Delicious pasta shells filled with spinach and cheese');
insert into authors (name, description) values ('Gwyneth Umpleby', 'Savory soup made with leeks and potatoes.');
insert into authors (name, description) values ('Demetris Salandino', 'Colorful building blocks for creative play.');
insert into authors (name, description) values ('Perl Colomb', 'Natural pink salt, perfect for seasoning.');
insert into authors (name, description) values ('Connor Staddon', 'Spicy salsa with chipotle and lime for a zesty kick.');
insert into authors (name, description) values ('Tansy Andrassy', 'Salty pretzels filled with creamy peanut butter.');
insert into authors (name, description) values ('Illa Pretty', 'Shredded potatoes, perfect for breakfasts.');
insert into authors (name, description) values ('Jeni O''Connell', 'Convenient carrier for transporting yoga mat.');
insert into authors (name, description) values ('Dale Isham', 'Warm oatmeal flavored with apple and cinnamon.');
insert into authors (name, description) values ('Gaye Revey', 'Classic wooden train set for imaginative play.');
insert into authors (name, description) values ('Misti Suller', 'Warm and stylish jacket for cold weather.');
insert into authors (name, description) values ('Evangeline Kemball', 'Tool to check car engine codes and performance issues.');
insert into authors (name, description) values ('Titos Jarrelt', 'Brews coffee with a smooth flavor without bitterness.');
insert into authors (name, description) values ('Alden Snowding', 'Double-walled mug to keep your drink hot for longer.');
insert into authors (name, description) values ('Cybil Swalwell', 'Quick-cooking ramen noodles made with organic wheat.');
insert into authors (name, description) values ('Cloris Jurick', 'Folding massage table for professional or home use.');
insert into authors (name, description) values ('Boycey Lantuff', 'Aromatic fresh basil, perfect for Italian cooking.');
insert into authors (name, description) values ('Essie Gravestone', 'Leak-proof cooler bag ideal for picnics and camping.');
insert into authors (name, description) values ('Isaac Garrow', 'Lightweight hammock for easy setup anywhere.');
insert into authors (name, description) values ('Ida McCowen', 'Eco-friendly bags for picking up after your pet.');
insert into authors (name, description) values ('Charlie Ubsdell', 'Light and crispy chips made from quinoa, ideal for dipping.');
insert into authors (name, description) values ('Fidelia Angelo', 'Chic suede ankle booties, perfect for dressing up or down.');
insert into authors (name, description) values ('Page Nan Carrow', 'Fun robot that engages kids with games and activities.');
insert into authors (name, description) values ('Yvonne Giraldo', 'Handmade eco-friendly bowls made from real coconuts.');
insert into authors (name, description) values ('Kellby Scrauniage', 'Plain white rice, a staple for any meal.');
insert into authors (name, description) values ('Suzie Youles', 'Grilled chicken skewers glazed with teriyaki sauce.');
insert into authors (name, description) values ('Morgan O''Spellissey', 'A hearty soup made with lentils, a variety of vegetables, and spices, ideal for a nutritious meal.');
insert into authors (name, description) values ('Bridget Gemmill', 'Creamy ranch dressing, perfect for salads and dips.');
insert into authors (name, description) values ('Kikelia Kenneford', 'Fresh green cabbage, great for salads and slaws.');
insert into authors (name, description) values ('Filip Sidwell', 'Creamy ice cream with a warm cinnamon flavor, perfect for dessert.');
insert into authors (name, description) values ('Chancey Rigardeau', 'Compact alarm for personal safety and security.');
insert into authors (name, description) values ('Rebekah Willimot', 'A blend of dried Italian herbs for cooking.');
insert into authors (name, description) values ('Woodrow Batty', 'Challenging puzzle game set for family entertainment.');
insert into authors (name, description) values ('Vera Ciccottio', 'Energy-efficient window air conditioner for cooling.');
insert into authors (name, description) values ('Bev Ciccone', 'Retro instant camera for capturing and printing photos instantly.');
insert into authors (name, description) values ('Deanna Whiffin', 'Just add water for delicious brownies.');
insert into authors (name, description) values ('Ebony Baynard', 'Organized tackle box for fishing gear.');
insert into authors (name, description) values ('Marten Shrubb', 'Flavorful chicken wings marinated in a sweet teriyaki glaze.');
insert into authors (name, description) values ('Chanda Sauvain', 'All-in-one kit for growing herbs in your kitchen.');
insert into authors (name, description) values ('Blaire Juszkiewicz', 'Juicy peach slices in light syrup, in convenient cups.');
insert into authors (name, description) values ('Chevalier Threadkell', 'A creamy blend of avocados and lime juice, great for spreads or dips.');
insert into authors (name, description) values ('Nicholle Kasper', 'Perfect dipping sauce or stir-fry addition for a sweet and tangy flavor.');
insert into authors (name, description) values ('Maribel Ogger', 'Crispy mini pretzels, a great snack any time of day.');
insert into authors (name, description) values ('Rafferty Jeannequin', 'Ergonomic memory foam pillow for better sleep.');
insert into authors (name, description) values ('Luz Keyte', 'Organizational cubes for easy packing and travel.');
insert into authors (name, description) values ('Eudora Ivanishchev', 'Fresh sliced bell peppers for salads or stir-fries.');
insert into authors (name, description) values ('Kevyn Sowersby', 'Durable jump rope for cardio workouts.');
insert into authors (name, description) values ('Seamus Pinwill', 'Stylish black leather jacket featuring a zip-up front and multiple pockets.');
insert into authors (name, description) values ('Filberte Van Merwe', 'Compact hair dryer with multiple heat settings.');
insert into authors (name, description) values ('Arabele Sallis', 'High in protein, perfect for soups and stews.');
insert into authors (name, description) values ('Emylee Britten', 'Adjustable footrest for improved comfort while sitting.');
insert into authors (name, description) values ('Findley Hutton', 'Ergonomic wireless mouse with adjustable DPI.');
insert into authors (name, description) values ('Becka Spenclay', 'Set of decorative pillow covers to enhance your home decor.');
insert into authors (name, description) values ('Adelheid Pearch', 'A cozy long cardigan designed for layering in any season.');
insert into authors (name, description) values ('Parry Hillhouse', 'Fun inflatable float for lounging in the pool or beach.');
insert into authors (name, description) values ('Maurise Leaf', 'Extra virgin olive oil infused with fresh basil.');
insert into authors (name, description) values ('Patrica Haycraft', 'Organize your board games with this storage bin.');
insert into authors (name, description) values ('Dorris Meth', 'A sweet and tangy dressing made with figs and balsamic vinegar, great on salads.');
insert into authors (name, description) values ('Rosalinda Orsay', 'Gluten-free tortillas made from almond flour, perfect for various wraps and meals.');
insert into authors (name, description) values ('Kenny O''Bradane', 'A zesty salad with black beans, corn, and chipotle dressing.');
insert into authors (name, description) values ('Juanita Marmon', 'Spicy jalapenos stuffed with cheese, ideal for appetizers.');
insert into authors (name, description) values ('Rori Jarret', 'Light and crispy rice cakes, a perfect low-calorie snack.');
insert into authors (name, description) values ('Maury Rockall', 'Stylish insulated lunch bag for on-the-go meals.');
insert into authors (name, description) values ('Greer Marsden', 'Soft and warm corn tortillas, perfect for tacos and burritos.');
insert into authors (name, description) values ('Maitilde Grinikhinov', 'Durable tarp for outdoor camping and protection.');
insert into authors (name, description) values ('Hayyim Russel', 'Tangy vinaigrette with orange and ginger flavors.');
insert into authors (name, description) values ('Suzanne Danne', 'Electric kettle that offers precise temperature settings.');
insert into authors (name, description) values ('Goddard Baton', 'DIY LED strip lights with remote control.');
insert into authors (name, description) values ('Kristyn Crenage', 'Light and crispy baked chips, a healthier snack option.');
insert into authors (name, description) values ('Dennis Zmitruk', 'Crunchy, seasoned chickpeas for a wholesome snack.');
insert into authors (name, description) values ('Mirabella Ronisch', 'Instant oatmeal cups with blueberries for an easy breakfast.');
insert into authors (name, description) values ('Claiborne Prettyman', 'Sustainable tank top made of bamboo cotton, offering breathability and comfort.');
insert into authors (name, description) values ('Consalve MacGuffie', 'Multi-functional gloves for planting and digging without tools.');
insert into authors (name, description) values ('Michael Willmett', 'Oven-roasted sliced turkey, perfect for sandwiches.');
insert into authors (name, description) values ('Atlanta Poncet', 'Precision digital scale for accurate cooking measurements.');
insert into authors (name, description) values ('Verina Keats', 'Stylish faux leather leggings for a trendy outfit.');

